# Generated by Django 3.0.5 on 2020-04-11 18:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='posibleCliente',
            fields=[
                ('idPosibleCliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('telefono', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999999999)])),
                ('email', models.CharField(max_length=30)),
                ('mensaje', models.TextField(max_length=350)),
                ('copiaMensaje', models.BooleanField(null=True)),
            ],
        ),
    ]
